---
name: Uptime Kuma
version: 2026.08.26
slug: uptime-kuma-cfm
description: Sistema autoalojado de Kuma que permite la ejecucion dentro de un iframe "Uptime Robot"
url: https://github.com/carferrer/uptime-kuma-cfm
image: "ghcr.io/carferrer/uptime-kuma-cfm"
image_tag: "latest"
webui: http://[HOST]:[PORT:3001]
init: false
arch: 
  - amd64
  - aarch64
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
discovery:
  - uptime_kuma
ingress: false
#ingress_port: 3001
#ingress_stream: true
panel: true
panel_icon: "mdi:server-network"
panel_title: "Uptime Kuma" 
