---
name: Uptime Kuma
version: 2026.08.31
slug: uptime-kuma-cfm
description: Sistema autoalojado de Kuma que permite la ejecucion dentro de un iframe "Uptime Robot"
url: https://github.com/carferrer/uptime-kuma-cfm
image: "ghcr.io/carferrer/uptime-kuma-cfm"
image_tag: "latest"
init: false
arch: 
  - amd64
  - aarch64
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
discovery:
  - uptime_kuma
