name: Actualizar CHANGELOG automáticamente

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Actualizar archivo CHANGELOG.md
        run: |
          # 1. Crear el archivo si no existe
          touch CHANGELOG.md
          
          # 2. Guardar el contenido actual temporalmente
          cat CHANGELOG.md > old_changelog.txt
          
          # 3. Escribir el título de la versión y las notas nativas de GitHub
          echo -e "# Versión ${{ github.event.release.tag_name }}\n" > CHANGELOG.md
          echo -e "${{ github.event.release.body }}\n" >> CHANGELOG.md
          
          # 4. Volver a añadir el historial antiguo debajo
          cat old_changelog.txt >> CHANGELOG.md
          
          # 5. Limpiar archivo temporal
          rm old_changelog.txt

      - name: Subir cambios al repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add CHANGELOG.md
          git commit -m "chore: actualizar CHANGELOG.md para la versión ${{ github.event.release.tag_name }} [skip ci]"
          git push
